version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=receipts_user
      - DB_PASSWORD=receipts_password
      - DB_NAME=receipts_db
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=receipts_db
      - MYSQL_USER=receipts_user
      - MYSQL_PASSWORD=receipts_password
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
